language: c
sudo: false

env:
  global:
    # RACKET_DIR is an argument to install-racket.sh
    - RACKET_DIR=~/racket
    - PATH="$RACKET_DIR/bin:$PATH"
  matrix:
    # RACKET_VERSION is an argument to install-racket.sh
    - RACKET_VERSION=6.4    COVER=false
    - RACKET_VERSION=6.5    COVER=false
    - RACKET_VERSION=6.6    COVER=false
    - RACKET_VERSION=6.7    COVER=false
    - RACKET_VERSION=6.8    COVER=false
    - RACKET_VERSION=6.9    COVER=true
    - RACKET_VERSION=6.10   COVER=true
    - RACKET_VERSION=6.10.1 COVER=true
    - RACKET_VERSION=6.11   COVER=true
    - RACKET_VERSION=6.12   COVER=true
    - RACKET_VERSION=7.0    COVER=true
    - RACKET_VERSION=7.1    COVER=true
    - RACKET_VERSION=7.2    COVER=true
    - RACKET_VERSION=HEAD   COVER=true

before_install:
- curl -L https://raw.githubusercontent.com/greghendershott/travis-racket/master/install-racket.sh | bash
- if $COVER; then raco pkg install --deps search-auto doc-coverage cover cover-codecov; fi # or cover-coveralls

install:
- raco pkg install --deps search-auto -j 2

script:
- raco test -r -p "$(basename "$TRAVIS_BUILD_DIR")"
- raco setup --check-pkg-deps --no-zo --no-launcher --no-install --no-post-install --no-docs --pkgs "$(basename "$TRAVIS_BUILD_DIR")"
#- if $COVER; then raco doc-coverage "$(basename "$TRAVIS_BUILD_DIR")"; fi
- if $COVER; then raco cover -s main -s test -s doc -f codecov -f html -d ~/coverage . || true; fi
# TODO: add an option to cover to run the "outer" module too, not just the submodules.
# TODO: deploy the coverage info.
